### ISSUE TITLE
Adding lookups prevents puppetdb from storing reports

### ISSUE THREAD

**Issue by witchbutter** [crayfishx/hiera-http#81]
Somehow adding this gem to the puppetserver ruby and including this stanza in my hiera.yaml caused PuppetDB to stop storing reports without reporting any actual errors in the logs:
```
  - name: "Hiera-HTTP lookup"
    lookup_key: hiera_http
    uris:
      - "http://localhost:8500/v1/kv/hiera/nodes/%{trusted.certname}__KEY__"
      - "http://localhost:8500/v1/kv/hiera/common/__KEY__"
      - "http://localhost:8500/v1/kv/hiera/__KEY__"
    options:
      output: json
      ignore_404: true
      dif: true
      dig_key: Value
      failure: graceful
```
I notice also that the compatibility list on the module doesn't include 16.04 and this is on a 16.04 server.  Is the compatibility list accurate?

Puppet 5.5.14, PuppetDB 5.2.8 on Postgres 9.6, Puppetserver 5.3.8
